// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/candidatos.tsx";
import * as $1 from "./routes/compartilhar-imagem.tsx";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/Candidatos.tsx";
import * as $$1 from "./islands/Home.tsx";

const manifest = {
  routes: {
    "./routes/candidatos.tsx": $0,
    "./routes/compartilhar-imagem.tsx": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/Candidatos.tsx": $$0,
    "./islands/Home.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
